services:
  tgbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tgbot
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    volumes:
      - ./tgbot:/app/tgbot

  db:
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  redis:
    image: redis:8.0-M03-alpine
    expose:
      - 6379

volumes:
  db:
